Numpy- Library used in numerical calculatioons.

In [1]:
import numpy as np

In [2]:
list = [1, 2, 3, 4, 5, 6, 7]

In [3]:
arr = np.array(list)

In [4]:
print(arr)

[1 2 3 4 5 6 7]


## Multi-dimensional Arrays

### A multi-dimensional array is an array with more than one dimensions(axis). It allows storing and processing data efficiency(2D array).

In [6]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2)
print('Shape:' , arr_2.shape)
print('Dimensions:' , arr_2.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


## Array Properties

In [8]:
print(arr_2.shape)
print(arr_2.ndim)
print(arr_2.)
print(arr_2.)

SyntaxError: invalid syntax (2202776423.py, line 3)

### Array Operations