Numpy- Library used in numerical calculatioons.

In [3]:
import numpy as np

In [4]:
list = [1, 2, 3, 4, 5, 6, 7]

In [5]:
arr = np.array(list)

In [6]:
print(arr)

[1 2 3 4 5 6 7]


## Multi-dimensional Arrays

### A multi-dimensional array is an array with more than one dimensions(axis). It allows storing and processing data efficiency(2D array).

In [7]:
arr_2 = np.array([[1, 2, 3],[4, 5, 6]])
print(arr_2)
print('Shape:' , arr_2.shape)
print('Dimensions:' , arr_2.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2


## Array Properties

In [9]:
print(arr_2.shape)
print(arr_2.ndim)
print(arr_2.size)
print(arr_2.dtype)

(2, 3)
2
6
int64


### Array Operations